### ISSUE TITLE
Bug: TypeError in SbbTable due to undefined _ngZone

### ISSUE THREAD

**Issue by scito** [sbb-design-systems/sbb-angular#1158]
**Describe the bug**

I get in core.mjs:6495
```
ERROR TypeError: Cannot read properties of undefined (reading 'runOutsideAngular')
    at SbbTable.ngOnInit (table.mjs:838:22)
    at callHook (core.mjs:2533:22)
    at callHooks (core.mjs:2502:17)
    at executeInitAndCheckHooks (core.mjs:2453:9)
    at selectIndexInternal (core.mjs:8424:17)
    at Module.ɵɵadvance (core.mjs:8407:5)
    at ErfassteAntraegeComponent_sbb_table_wrapper_0_table_1_Template (erfasste-antraege.component.html:237:25)
    at executeTemplate (core.mjs:9637:9)
    at refreshView (core.mjs:9503:13)
    at refreshEmbeddedViews (core.mjs:10628:17)
```

My code is working with 13.0.0, but not with version 13.1.0 or 13.5.0

It seems _ngZone does not exist anymore in SbbTable (table.ts) and was replaced with ngZone. But _ngZone is still used in line 130 of table.ts.

The issues seems to come in commit 5ffe9391db5dfcbd8a3ba01726e6c4af6c97b520 of issue #1019.

This error is triggered by
```
<tr sbb-header-row *sbbHeaderRowDef="displayedColumns; sticky: true"></tr>
```

**Expected behavior**
No TypeError

**Comment by jeripeierSBB** [comment]
Hi @scito 

this is probably cdk related. Which cdk version do you use?

**Comment by scito** [comment]
@jeripeierSBB 
"@angular/cdk": "^13.0.2",
