### ISSUE TITLE
[Bug]: DatePicker seems to not work, when used within a sbbDialog

### ISSUE THREAD

**Issue by andreastausend** [sbb-design-systems/sbb-angular#2066]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/sbb-angular/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/sbb-angular/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/1) for an issue that matches the one I want to file, without success.

### Bug type

Functionality

### Which version are you using

16.7.1

### Operating system

Ubuntu

### Browser / Browser version

Chrome Version 118.0.5993.118 (Official Build) (64-bit)

### Input mode

None

### What happened?

I am trying to use Sbb Angular’s Datepicker (https://angular.app.sbb.ch/angular/components/datepicker/overview). When using it as shown in the example in a proper component, it works as expected. But I would like to use it in a Dialog Compoment (https://angular.app.sbb.ch/angular/components/dialog/overview). For some reason the same typescript and html-code in that case lead to an error:

core.mjs:10592 ERROR Error: SbbDatepicker: No provider found for DateAdapter.
    at createMissingDateImplError (datepicker.mjs:192:12)
    at new SbbCalendar (datepicker.mjs:785:19)
    at NodeInjectorFactory.SbbCalendar_Factory [as factory] (datepicker.mjs:868:23)
    at getNodeInjectable (core.mjs:4758:44)
    at instantiateAllDirectives (core.mjs:12612:27)
    at createDirectivesInstances (core.mjs:12028:5)
    at Module.ɵɵelementStart (core.mjs:16319:9)
    at SbbDatepickerContent_Template (datepicker.mjs:151:103)
    at executeTemplate (core.mjs:11986:13)
    at renderView (core.mjs:13184:13)

I was not able to figure out how to resolve this. I would be glad if you could help me out here.

### Steps to reproduce the issue

did not try it from scratch, but i guess creating a compomponent, that opens a dialog and adding a datepicker there will lead to the error, when clicking on the date-selection-field

### Relevant log output

```shell
core.mjs:10592 ERROR Error: SbbDatepicker: No provider found for DateAdapter.
    at createMissingDateImplError (datepicker.mjs:192:12)
    at new SbbCalendar (datepicker.mjs:785:19)
    at NodeInjectorFactory.SbbCalendar_Factory [as factory] (datepicker.mjs:868:23)
    at getNodeInjectable (core.mjs:4758:44)
    at instantiateAllDirectives (core.mjs:12612:27)
    at createDirectivesInstances (core.mjs:12028:5)
    at Module.ɵɵelementStart (core.mjs:16319:9)
    at SbbDatepickerContent_Template (datepicker.mjs:151:103)
    at executeTemplate (core.mjs:11986:13)
    at renderView (core.mjs:13184:13)
```

**Comment by mhaertwig** [comment]
@andreastausend, thanks for the bug report. I am still investigating it. A quick-fix is to add the `SbbDatepickerModule` to the imports of the `ComponentDataDialogExample`.
